spring:
    datasource:
        driver-class-name: com.ibm.db2.jcc.DB2Driver
        password: Test
        url: jdbc:db2://123.123.com:55000/
        username: Test
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.DB2Dialect
        show-sql: true
